version: '3.5'

services:
  squidcustom:
    image: ${SQUID_IMAGE:-ubuntu/squid:5.2-22.04_beta}
    volumes:
      - $PWD/spec/fixtures/squidcustom/squid.conf:/etc/squid/squid.conf
      - $PWD/spec/fixtures/squidcustom/passwords:/etc/squid/passwords
    healthcheck:
      interval: 5s
      retries: 10
      test: ["CMD", "kill", "-0", "1"]
      timeout: 10s
    restart: on-failure
    stop_signal: SIGKILL
    networks:
      - ${NETWORK_NAME}
