version: '3.5'

services:
  ad-server:
    image: ad-server
    build:
      context: ${PWD}/.pongo/ad-server/
      dockerfile: Dockerfile
    # needs priv due to a bug described in the Dockerfile
    privileged: true
    # healthcheck:
    #   interval: 5s
    #   retries: 10
    #   test:
    #   - CMD
    #   - 'true'
      # TODO, how to verify if samba is ready..!
      # timeout: 10s
    restart: on-failure
    stop_signal: SIGKILL
    ports:
      - 127.0.0.1::389
      - 127.0.0.1::636
    networks:
      - ${NETWORK_NAME}