# Set update schedule for GitHub Actions

version: 2

registries:
  npm:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{ secrets.NPM_TOKEN_PRIVATE_READ }}

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"

  - package-ecosystem: npm
    directory: "/spec-ee/kong-api-tests"
    schedule:
      interval: daily
    ignore: # ignore major updates
      - dependency-name: '*'
        update-types: [version-update:semver-major]
