# please see matrix-full.yml for meaning of each field
build-packages:
- label: ubuntu-22.04
  os: vars.RELEASE_RUNS_ON
  package: deb
  check-manifest-suite: ubuntu-22.04-amd64
- label: ubuntu-22.04-arm64
  os: vars.RELEASE_RUNS_ON
  package: deb
  bazel-args: --platforms=//:generic-crossbuild-aarch64 --//:wasmx=false
  check-manifest-suite: ubuntu-22.04-arm64

build-images:
- label: ubuntu
  base-image: ubuntu:22.04
  package: deb
  artifact-from: ubuntu-22.04
  artifact-from-alt: ubuntu-22.04-arm64
  docker-platforms: linux/amd64, linux/arm64

test-images:
- label: ubuntu
  multiarch: true

smoke-tests:
- label: ubuntu

scan-vulnerabilities:
- label: ubuntu

release-packages:

release-images:
- label: ubuntu
  package: deb
