dist: xenial
sudo: false

language: generic

jdk:
  - oraclejdk8

notifications:
  email:
    on_success: never
    on_failure: always

services:
  - redis-server
  - docker

addons:
  postgresql: "9.5"
  apt:
    packages:
      - net-tools
      - libpcre3-dev
      - libpasswdqc-dev
      - build-essential
  hosts:
    - grpcs_1.test
    - grpcs_2.test

env:
  global:
    - INSTALL_CACHE=$HOME/install-cache
    - DOWNLOAD_ROOT=$HOME/download-root
    - KONG_TEST_PG_DATABASE=travis
    - KONG_TEST_PG_USER=postgres
    - JOBS=2
    - DOCKER_MACHINE_ARM64_NAME=travis-ci-kong-${TRAVIS_JOB_ID}
  matrix:
    # enterprise matrix begin
    # XXX add extra jobs for different cassandra versions
    - KONG_TEST_DATABASE=postgres TEST_SUITE=integration-ee
    - KONG_TEST_DATABASE=cassandra CASSANDRA=2.2 TEST_SUITE=integration-ee
    - KONG_TEST_DATABASE=cassandra CASSANDRA=3.9 TEST_SUITE=integration-ee
    - KONG_TEST_DATABASE=cassandra CASSANDRA=2.2 TEST_SUITE=plugins-ee
    - KONG_TEST_DATABASE=cassandra CASSANDRA=3.9 TEST_SUITE=plugins-ee
    - KONG_TEST_DATABASE=postgres TEST_SUITE=plugins-ee
    # enterprise matrix end
    - KONG_TEST_DATABASE=postgres TEST_SUITE=integration
    - KONG_TEST_DATABASE=cassandra CASSANDRA=2.2 TEST_SUITE=integration
    - KONG_TEST_DATABASE=cassandra CASSANDRA=3.9 TEST_SUITE=integration
    # - KONG_TEST_DATABASE=off TEST_SUITE=dbless # XXX EE no dbless in enterprise
    - KONG_TEST_DATABASE=postgres TEST_SUITE=plugins
    - KONG_TEST_DATABASE=cassandra CASSANDRA=2.2 TEST_SUITE=plugins
    - KONG_TEST_DATABASE=cassandra CASSANDRA=3.9 TEST_SUITE=plugins
    - TEST_SUITE=pdk

install:
  - source .ci/setup_env.sh
  - make dev

cache:
  apt: true
  directories:
    - $INSTALL_CACHE
    - $HOME/.ccm/repository

stages:
  - lint and unit
  - test
  - name: deploy
    if: tag =~ 0. || type == cron || branch = master
  # - functional tests
  # # - Deploy daily build
  # - Release

jobs:
  include:
    - stage: lint and unit
      script:
      - luacheck -q .
      # - scripts/autodoc-admin-api
      - bin/busted -v -o gtest spec/01-unit
      - bin/busted -v -o gtest spec-ee/01-unit
      env:
        - KONG_DATABASE=none
    - stage: deploy
      if: branch = master
      script: .ci/build_artifacts.sh
      env:
        - DOCKER_TAG_NAME=dev-master
        - TEST_SUITE=none
    - stage: deploy
      if: tag =~ 0.
      script: .ci/build_artifacts.sh
      env:
        - DOCKER_TAG_NAME=released
        - TEST_SUITE=none
    - stage: deploy
      if: tag =~ 0.
      script: .ci/trigger-travis.sh --pro $TRAVIS_ACCESS_TOKEN

script:
  - .ci/run_tests.sh
