dist: xenial
sudo: false

language: generic

jdk:
  - oraclejdk8

notifications:
  email:
    on_success: never
    on_failure: always

services:
  - redis-server
  - docker

addons:
  postgresql: "9.5"
  apt:
    packages:
      - net-tools
      - libpcre3-dev
      - libpasswdqc-dev
      - build-essential
  hosts:
    - grpcs_1.test
    - grpcs_2.test

env:
  global:
    - INSTALL_CACHE=$HOME/install-cache
    - DOWNLOAD_ROOT=$HOME/download-root
    - KONG_TEST_PG_DATABASE=travis
    - KONG_TEST_PG_USER=postgres
    - JOBS=2
    - DOCKER_MACHINE_ARM64_NAME=travis-ci-kong-${TRAVIS_JOB_ID}
    - DOCKER_USERNAME=kongcloudpull
    - secure: "MB/RJAWPgZ8+c7qt3YQ08nLMI3GPdqyGWY3bxMvZ7EbJtqStEkJDqe40ag1PYmCodieCyS/O5dT3yd+KYIuS5CRX6SNBUriUDbzqJmVrcZxof1IiiLJCKw52R1/pHTrZ5ajpnJiC2cBageQTrqYBBFez65zMZlJQfTDY8xVAFhM4Z07GnCDFzCJVv4qbZwMfnnXD2nLBuK3lwwcfzn0zZNNZ+hqGRl8l95pPx/eaJc36VsyMWmPilKbd4AH4zCPoBrPxLucbNaGjHwImAvFSsQurdYlSymS4ghsPljWW9FEUarjg+OtiDhCpCn2bXYdmplmY0WXeBXy04LBKmKJLZzVLhzvaI+CeJBQxjJCsMcHPGXwibtLPd0IloBEzqxgcRs1rPzUlPg6romdqehB53vOhZNO1l5Zft8AiCCfxnzpUF/8GZJgrXP5OMnT+I9j/+RUjT30vni9NSDQw467jrnDZ8aP4WeRSZwviJPLaT2nTeKMMqQSXm+sBo0grhEnxSpQIp+WgVKTbUyZkUlNg6FYu1iA9KPmlXNXvw3+9fR83vV6xM3xx9B75lM/SDgl2WZco9m6WvhgzohE8rjO9zS/oKSH91XJVzY0ox4Qtt4Ph+uo1TMiS1W3D22oFpThuyg2BlMKAm1pTlE7mE1jt7FwC82/BMOh3l2lxFv3c53s="
  matrix:
    # enterprise matrix begin
    # XXX add extra jobs for different cassandra versions
    - KONG_TEST_DATABASE=postgres TEST_SUITE=integration-ee
    - KONG_TEST_DATABASE=cassandra CASSANDRA=3.11 TEST_SUITE=integration-ee
    - KONG_TEST_DATABASE=cassandra CASSANDRA=3.11 TEST_SUITE=plugins-ee
    - KONG_TEST_DATABASE=postgres TEST_SUITE=plugins-ee
    # enterprise matrix end
    - KONG_TEST_DATABASE=postgres TEST_SUITE=integration
    - KONG_TEST_DATABASE=cassandra CASSANDRA=3.11 TEST_SUITE=integration
    # - KONG_TEST_DATABASE=off TEST_SUITE=dbless # XXX EE no dbless in enterprise
    - KONG_TEST_DATABASE=postgres TEST_SUITE=plugins
    - KONG_TEST_DATABASE=cassandra CASSANDRA=3.11 TEST_SUITE=plugins
    - TEST_SUITE=pdk

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - source .ci/setup_env.sh
  - make dev

cache:
  apt: true
  directories:
    - $INSTALL_CACHE
    - $HOME/.ccm/repository

stages:
  - lint and unit
  - test

jobs:
  include:
    - stage: lint and unit
      script:
      - make lint
      - bin/busted -v -o gtest spec/01-unit
      - bin/busted -v -o gtest spec-ee/01-unit
      env:
        - KONG_DATABASE=none
script:
  - .ci/run_tests.sh
