dist: xenial

language: go

go:
  - "1.13.x"

notifications:
  slack:
    if: branch = master AND type != pull_request
    on_success: change
    on_failure: always
    rooms:
      secure: B8NkX4SKLbr3fm5luTjnfzni12foriINUbwCyXWkcJ6g+U9cpg8cxPswvozIYEdGJDNPHf5kyBPYRVPjJfGzlHD4cgiytK7pcW8zkrjb2tyTzJNdkuYwAWylO73OHFHNoF4jAtcYDs9939oqdK124K+NZKS423QjB7LSFgrCXO6kattOdMGj6UnL0xeuooQ5dfCXLKpsnwbT2WQoUk4yeDo170tGwDi2jgN61a76ImU3tbrr2GQJwAwj3hwVtwfsmIVq1xdZefz618GYaByvW46vQ7XwxUZZiWJehDHqCQR//tqjPSV6PmtOPUUkfgBEbeR47k8qGBoIlaOc2ZkdvkpAj2ugyRIp0ReqJN5DRd6ErGk4MTWiDB9c6kmB+kjy61taDWKly/hZtK+rl6pYZcG14KEBJAdm+LM0f2L3IhB4myUB9gjc2Tc/tqBYitmK9cmwwr6OtgrCpibicRsYH8Ap7ojdDaoOBab+8aEYHlvrlIj0Zf9dpsK8aHOoqW3KXtJwEDG1apEtI+tPtfQiC6DqFA9V1MvcFXl/MUatsC3VkkZAq5VdSZHDKPkIdfeDuP8Wv//kHdt8o0sDC+6DyZrqkl3VBSGAXrSw6zJbXMCNvymtfCMFh/6I9GJBSAEzSxGD4weiMe65gwo6wHKnS/JaxNe2KCKx2Qo9YLMWG7w=

services:
  - redis-server
  - docker

addons:
  postgresql: "9.5"
  apt:
    packages:
      - net-tools
      - libpcre3-dev
      - libpasswdqc-dev
      - valgrind
      - build-essential
  hosts:
    - grpcs_1.test
    - grpcs_2.test

env:
  global:
    - INSTALL_CACHE=$HOME/install-cache
    - DOWNLOAD_ROOT=$HOME/download-root
    - KONG_TEST_PG_DATABASE=travis
    - KONG_TEST_PG_USER=travis
    - KONG_TEST_PG_RO_USER=travis_ro
    - KONG_TEST_PG_HOST=localhost
    - JOBS=2
    - DOCKER_MACHINE_ARM64_NAME=travis-ci-kong-${TRAVIS_JOB_ID}
    # Related to packaging and master build
    - KONG_DISTRIBUTIONS_VERSION=master
    - CACHE_DIR=$HOME/distributions-cache
    - ENABLE_OPENTRACING=0
    - DOCKER_USERNAME=kongcloudpull
    - secure: "MB/RJAWPgZ8+c7qt3YQ08nLMI3GPdqyGWY3bxMvZ7EbJtqStEkJDqe40ag1PYmCodieCyS/O5dT3yd+KYIuS5CRX6SNBUriUDbzqJmVrcZxof1IiiLJCKw52R1/pHTrZ5ajpnJiC2cBageQTrqYBBFez65zMZlJQfTDY8xVAFhM4Z07GnCDFzCJVv4qbZwMfnnXD2nLBuK3lwwcfzn0zZNNZ+hqGRl8l95pPx/eaJc36VsyMWmPilKbd4AH4zCPoBrPxLucbNaGjHwImAvFSsQurdYlSymS4ghsPljWW9FEUarjg+OtiDhCpCn2bXYdmplmY0WXeBXy04LBKmKJLZzVLhzvaI+CeJBQxjJCsMcHPGXwibtLPd0IloBEzqxgcRs1rPzUlPg6romdqehB53vOhZNO1l5Zft8AiCCfxnzpUF/8GZJgrXP5OMnT+I9j/+RUjT30vni9NSDQw467jrnDZ8aP4WeRSZwviJPLaT2nTeKMMqQSXm+sBo0grhEnxSpQIp+WgVKTbUyZkUlNg6FYu1iA9KPmlXNXvw3+9fR83vV6xM3xx9B75lM/SDgl2WZco9m6WvhgzohE8rjO9zS/oKSH91XJVzY0ox4Qtt4Ph+uo1TMiS1W3D22oFpThuyg2BlMKAm1pTlE7mE1jt7FwC82/BMOh3l2lxFv3c53s="
  matrix:
    # enterprise matrix begin
    # XXX add extra jobs for different cassandra versions
    - KONG_TEST_DATABASE=postgres TEST_SUITE=integration-ee
    - KONG_TEST_DATABASE=cassandra CASSANDRA=3.11 TEST_SUITE=integration-ee
    - KONG_TEST_DATABASE=cassandra CASSANDRA=3.11 TEST_SUITE=plugins-ee
    - KONG_TEST_DATABASE=postgres TEST_SUITE=plugins-ee
    # enterprise matrix end
    - KONG_TEST_DATABASE=postgres TEST_SUITE=integration
    - KONG_TEST_DATABASE=cassandra CASSANDRA=3.11 TEST_SUITE=integration
    - KONG_TEST_DATABASE=off TEST_SUITE=dbless
    - KONG_TEST_DATABASE=postgres TEST_SUITE=plugins
    - KONG_TEST_DATABASE=cassandra CASSANDRA=3.11 TEST_SUITE=plugins
    - TEST_SUITE=pdk

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - source .ci/setup_env.sh
  - make dev

cache:
  apt: true
  directories:
    - $INSTALL_CACHE
    - $HOME/.ccm/repository
    - $HOME/distributions-cache

before_cache:
  # files in distributions cache have been created within docker, so it's
  # completely possible that travis user would not have full permissions
  - sudo chown -R travis:travis $HOME/distributions-cache

stages:
  - lint and unit
  - test

jobs:
  include:
    - stage: lint and unit
      script:
      - make lint
      - bin/busted -v -o htest spec/01-unit --exclude-tags=flaky
      - bin/busted -v -o htest spec-ee/01-unit --exclude-tags=flaky
      - scripts/autodoc-admin-api
      env:
        - KONG_DATABASE=none
script:
  - .ci/run_tests.sh
