dist: trusty
sudo: required

language: java

jdk:
  - oraclejdk8

notifications:
  email: false

services:
  - redis-server

addons:
  postgresql: "9.5"
  apt:
    packages:
      - net-tools
      - libpcre3-dev
      - build-essential

services:
  - redis
  - docker

env:
  global:
    - LUAROCKS=2.4.3
    - OPENSSL=1.0.2n
    - CASSANDRA=3.9
    - OPENRESTY_BASE=1.13.6.2
    - OPENRESTY_LATEST=1.13.6.2
    - OPENRESTY=$OPENRESTY_BASE
    - DOWNLOAD_CACHE=$HOME/download-cache
    - INSTALL_CACHE=$HOME/install-cache
  matrix:
    - TEST_SUITE=lint
    - TEST_SUITE=unit
    - TEST_SUITE=integration
      OPENRESTY=$OPENRESTY_LATEST
    - TEST_SUITE=plugins
      OPENRESTY=$OPENRESTY_LATEST
    - TEST_SUITE=integration
      OPENRESTY=$OPENRESTY_BASE
      CASSANDRA=2.2.12
    - TEST_SUITE=plugins
      OPENRESTY=$OPENRESTY_BASE
      CASSANDRA=2.2.12
    - TEST_SUITE=old-unit
    - TEST_SUITE=old-integration
      OPENRESTY=$OPENRESTY_BASE
    - TEST_SUITE=old-plugins
      OPENRESTY=$OPENRESTY_BASE

before_install:
  - source .ci/setup_env.sh

install:
  - make dev

script:
  - .ci/run_tests.sh

jobs:
  include:
    - stage: deploy
      if: branch = master
      script: .ci/build_docker_image.sh
      env:
        - DOCKER_TAG_NAME=dev-master
        - TEST_SUITE=none
    - stage: deploy
      if: tag =~ 0.
      script: .ci/build_docker_image.sh
      env:
        - DOCKER_TAG_NAME=released
        - TEST_SUITE=none
    - stage: deploy
      if: tag =~ 0.
      script: .ci/trigger-travis.sh --pro $TRAVIS_ACCESS_TOKEN
      

cache:
  apt: true
  pip: true
  directories:
    - $DOWNLOAD_CACHE
    - $INSTALL_CACHE
    - $HOME/.ccm/repository


branches:
  except:
    - feat/entity-level-rbac
