dist: trusty
sudo: false

language: java

jdk:
  - oraclejdk8

notifications:
  email: false

addons:
  postgresql: "9.5"
  apt:
    packages:
      - net-tools
      - libpcre3-dev
      - build-essential

services:
  - redis
  - docker

env:
  global:
    - LUAROCKS=2.4.2
    - OPENSSL=1.0.2l
    - CASSANDRA=2.2.8
    - OPENRESTY_BASE=1.11.2.4
    - OPENRESTY_LATEST=1.11.2.4
    - OPENRESTY=$OPENRESTY_BASE
    - DOWNLOAD_CACHE=$HOME/download-cache
    - INSTALL_CACHE=$HOME/install-cache
  matrix:
    - TEST_SUITE=lint
    - TEST_SUITE=unit
    - TEST_SUITE=integration
      OPENRESTY=$OPENRESTY_BASE
    - TEST_SUITE=plugins
      OPENRESTY=$OPENRESTY_BASE
    - TEST_SUITE=integration
      OPENRESTY=$OPENRESTY_LATEST
      CASSANDRA=3.9
    - TEST_SUITE=plugins
      OPENRESTY=$OPENRESTY_LATEST
      CASSANDRA=3.9

before_install:
  - source .ci/setup_env.sh

install:
  - make dev

script:
  - .ci/run_tests.sh

deploy:
  - provider: script
    script: DOCKER_TAG_NAME=dev-master .ci/build_docker_image.sh; fi
    on:
      branch: master

  - provider: script
    script: DOCKER_TAG_NAME=released .ci/build_docker_image.sh; fi
    on:
      tags: true

cache:
  apt: true
  pip: true
  directories:
    - $DOWNLOAD_CACHE
    - $INSTALL_CACHE
    - $HOME/.ccm/repository
