dist: xenial

language: go

go:
  - "1.13.x"

notifications:
  slack:
    if: branch = master AND type != pull_request
    on_success: change
    on_failure: always
    rooms:
      secure: B8NkX4SKLbr3fm5luTjnfzni12foriINUbwCyXWkcJ6g+U9cpg8cxPswvozIYEdGJDNPHf5kyBPYRVPjJfGzlHD4cgiytK7pcW8zkrjb2tyTzJNdkuYwAWylO73OHFHNoF4jAtcYDs9939oqdK124K+NZKS423QjB7LSFgrCXO6kattOdMGj6UnL0xeuooQ5dfCXLKpsnwbT2WQoUk4yeDo170tGwDi2jgN61a76ImU3tbrr2GQJwAwj3hwVtwfsmIVq1xdZefz618GYaByvW46vQ7XwxUZZiWJehDHqCQR//tqjPSV6PmtOPUUkfgBEbeR47k8qGBoIlaOc2ZkdvkpAj2ugyRIp0ReqJN5DRd6ErGk4MTWiDB9c6kmB+kjy61taDWKly/hZtK+rl6pYZcG14KEBJAdm+LM0f2L3IhB4myUB9gjc2Tc/tqBYitmK9cmwwr6OtgrCpibicRsYH8Ap7ojdDaoOBab+8aEYHlvrlIj0Zf9dpsK8aHOoqW3KXtJwEDG1apEtI+tPtfQiC6DqFA9V1MvcFXl/MUatsC3VkkZAq5VdSZHDKPkIdfeDuP8Wv//kHdt8o0sDC+6DyZrqkl3VBSGAXrSw6zJbXMCNvymtfCMFh/6I9GJBSAEzSxGD4weiMe65gwo6wHKnS/JaxNe2KCKx2Qo9YLMWG7w=

services:
  - redis-server
  - docker

addons:
  postgresql: "9.5"
  apt:
    packages:
      - net-tools
      - libpcre3-dev
      - libpasswdqc-dev
      - valgrind
      - build-essential
  hosts:
    - grpcs_1.test
    - grpcs_2.test
    - grpcbin

env:
  global:
    - INSTALL_CACHE=$HOME/install-cache
    - DOWNLOAD_ROOT=$HOME/download-root
    - KONG_TEST_PG_DATABASE=travis
    - KONG_TEST_PG_USER=travis
    - KONG_TEST_PG_RO_USER=travis_ro
    - KONG_TEST_PG_HOST=localhost
    - JOBS=2
    - DOCKER_MACHINE_ARM64_NAME=travis-ci-kong-${TRAVIS_JOB_ID}
    # Related to packaging and master build
    - KONG_DISTRIBUTIONS_VERSION=master
    - CACHE_DIR=$HOME/distributions-cache
    - ENABLE_OPENTRACING=0
  matrix:
    # enterprise matrix begin
    # XXX add extra jobs for different cassandra versions
    - KONG_TEST_DATABASE=postgres TEST_SUITE=integration-ee
    - KONG_TEST_DATABASE=cassandra CASSANDRA=3.9 TEST_SUITE=integration-ee
    - KONG_TEST_DATABASE=cassandra CASSANDRA=3.9 TEST_SUITE=plugins-ee
    - KONG_TEST_DATABASE=postgres TEST_SUITE=plugins-ee
    # enterprise matrix end
    - KONG_TEST_DATABASE=postgres TEST_SUITE=integration
    - KONG_TEST_DATABASE=cassandra CASSANDRA=3.9 TEST_SUITE=integration
    - KONG_TEST_DATABASE=off TEST_SUITE=dbless
    - KONG_TEST_DATABASE=postgres TEST_SUITE=plugins
    - KONG_TEST_DATABASE=cassandra CASSANDRA=3.9 TEST_SUITE=plugins
    - TEST_SUITE=pdk

install:
  - source .ci/setup_env.sh
  - make dev

cache:
  apt: true
  directories:
    - $INSTALL_CACHE
    - $HOME/.ccm/repository
    - $HOME/distributions-cache

before_cache:
  # files in distributions cache have been created within docker, so it's
  # completely possible that travis user would not have full permissions
  - sudo chown -R travis:travis $HOME/distributions-cache

stages:
  - lint and unit
  - test
  - name: package
  - name: deploy
    if: tag =~ 0. || type == cron || branch = master

jobs:
  include:
    - stage: lint and unit
      script:
      - make lint
      # - scripts/autodoc
      - bin/busted -v -o htest spec/01-unit --exclude-tags=flaky
      - bin/busted -v -o htest spec-ee/01-unit --exclude-tags=flaky
      - scripts/autodoc
      env:
        - KONG_DATABASE=none
    # package as a test step, to see if this commit breaks our packaging
    # useful for testing changes in .ci packaging, uncomment to see effects
    # it's not terrible if it's uncommented. But it will break for any PR not
    # targeted at current kong master
    # (unless proper KONG_DISTRIBUTIONS_VERSION branch is set)
    # - stage: package
    #   if: branch != master
    #   script: .ci/build_package.sh
    # package and release, only on master
    - stage: package and deploy
      if: branch = master
      script: .ci/build_package.sh && .ci/release_artifacts.sh

script:
  - .ci/run_tests.sh
