dist: xenial

language: generic

jdk:
  - oraclejdk8

go:
  - "1.13.x"

notifications:
  email:
    on_success: never
    on_failure: always

services:
  - redis-server
  - docker

addons:
  postgresql: "9.5"
  apt:
    packages:
      - net-tools
      - libpcre3-dev
      - libpasswdqc-dev
      - build-essential
  hosts:
    - grpcs_1.test
    - grpcs_2.test

env:
  global:
    - INSTALL_CACHE=$HOME/install-cache
    - DOWNLOAD_ROOT=$HOME/download-root
    - KONG_TEST_PG_DATABASE=travis
    - KONG_TEST_PG_USER=postgres
    - JOBS=2
    - DOCKER_MACHINE_ARM64_NAME=travis-ci-kong-${TRAVIS_JOB_ID}
    # Related to packaging and master build
    - KONG_DISTRIBUTIONS_VERSION=refactor/rename-refactor-redo-package
    - CACHE_DIR=$HOME/distributions-cache
    - DOCKER_TAG_NAME=dev-master
    - ENABLE_OPENTRACING=0
  matrix:
    # enterprise matrix begin
    # XXX add extra jobs for different cassandra versions
    - KONG_TEST_DATABASE=postgres TEST_SUITE=integration-ee
    - KONG_TEST_DATABASE=cassandra CASSANDRA=2.2 TEST_SUITE=integration-ee
    - KONG_TEST_DATABASE=cassandra CASSANDRA=3.9 TEST_SUITE=integration-ee
    - KONG_TEST_DATABASE=cassandra CASSANDRA=2.2 TEST_SUITE=plugins-ee
    - KONG_TEST_DATABASE=cassandra CASSANDRA=3.9 TEST_SUITE=plugins-ee
    - KONG_TEST_DATABASE=postgres TEST_SUITE=plugins-ee
    # enterprise matrix end
    - KONG_TEST_DATABASE=postgres TEST_SUITE=integration
    - KONG_TEST_DATABASE=cassandra CASSANDRA=2.2 TEST_SUITE=integration
    - KONG_TEST_DATABASE=cassandra CASSANDRA=3.9 TEST_SUITE=integration
    # - KONG_TEST_DATABASE=off TEST_SUITE=dbless # XXX EE no dbless in enterprise
    - KONG_TEST_DATABASE=postgres TEST_SUITE=plugins
    - KONG_TEST_DATABASE=cassandra CASSANDRA=2.2 TEST_SUITE=plugins
    - KONG_TEST_DATABASE=cassandra CASSANDRA=3.9 TEST_SUITE=plugins
    - TEST_SUITE=pdk

install:
  - source .ci/setup_env.sh
  - make dev

cache:
  apt: true
  directories:
    - $INSTALL_CACHE
    - $HOME/.ccm/repository
    - $HOME/distributions-cache

stages:
  - lint and unit
  - test
  - name: package
  - name: deploy
    if: tag =~ 0. || type == cron || branch = master

jobs:
  include:
    - stage: lint and unit
      script:
      - luacheck -q .
      # - scripts/autodoc-admin-api
      - bin/busted -v -o gtest spec/01-unit
      - bin/busted -v -o gtest spec-ee/01-unit
      env:
        - KONG_DATABASE=none
    # package as a test step, to see if this commit breaks our packaging
    # useful for testing changes in .ci packaging, uncomment to see effects
    # it's not terrible if it's uncommented. But it will break for any PR not
    # targeted at current kong master
    # (unless proper KONG_DISTRIBUTIONS_VERSION branch is set)
    - stage: package
      if: branch != master
      script: .ci/build_package.sh
    # package and release, only on master
    - stage: package and deploy
      if: branch = master
      script: .ci/build_package.sh && .ci/release_artifacts.sh

script:
  - .ci/run_tests.sh
