version: '3.5'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:${PONGO_KEYCLOAK_VERSION:-24.0}
    command: start-dev --import-realm
    volumes:
      - ${PONGO_WD}/../openid-connect/.pongo/demo.json:/opt/keycloak/data/import/demo.json
      - ${PONGO_WD}/../openid-connect/.pongo/truststore.jks:/tmp/truststore.jks
      - ${PONGO_WD}/../openid-connect/.pongo/server.crt:/tmp/server.crt
      - ${PONGO_WD}/../openid-connect/.pongo/server.key:/tmp/server.key
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: test
      VIRTUAL_PORT: 8080,8443
      DB_VENDOR: h2
      JAVA_OPTS_APPEND: -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
      KC_HTTPS_TRUST_STORE_FILE: /tmp/truststore.jks
      KC_HTTPS_TRUST_STORE_PASSWORD: password
      KC_HTTPS_CLIENT_AUTH: request
      KC_HTTPS_PROTOCOLS: TLSv1.2
      KC_HTTPS_CERTIFICATE_FILE: /tmp/server.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /tmp/server.key
      KC_FEATURES: dpop
    healthcheck:
      interval: 5s
      retries: 10
      test:
      - CMD
      - timeout
      - 3s
      - bash
      - -c
      - ':> /dev/tcp/127.0.0.1/8080'
      timeout: 10s
    ports:
      - "127.0.0.1::8080"
      - "127.0.0.1::8443"
    restart: on-failure
    stop_signal: SIGKILL
    networks:
      - ${NETWORK_NAME}
