version: '3.5'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:${PONGO_KEYCLOAK_VERSION:-22.0}
    command:
      - start-dev
      - --import-realm
    volumes:
      - ${PONGO_WD}/.pongo/demo-realm.json:/opt/keycloak/data/import/demo-realm.json
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: test
      VIRTUAL_PORT: 8080
      DB_VENDOR: h2
      JAVA_OPTS_APPEND: -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
    ports:
      # temporary exposure of port, Pongo should not need this
      - "8080:8080"
      - "8543:8443"
    healthcheck:
      interval: 5s
      retries: 10
      test:
      - CMD
      - timeout
      - 3s
      - bash
      - -c
      - ':> /dev/tcp/127.0.0.1/8080'
      timeout: 10s
    restart: on-failure
    stop_signal: SIGKILL
    networks:
      - ${NETWORK_NAME}
