name: Autodocs

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (e.g. 2.4.x)"
        required: true
      source_branch:
        description: "Source Branch in kong/kong (e.g. release/2.4.x)"
        required: true
      target_branch:
        description: "Target Branch in kong/docs.konghq.com (e.g. release/2.4)"
        required: true
      force_build:
        description: "Ignore the build cache and build dependencies from scratch"
        type: boolean
        default: false
env:
  BUILD_ROOT: ${{ github.workspace }}/bazel-bin/build
  BUILD_NAME: kong-dev-normal
  BUILD_NAME_NORMAL: kong-dev-normal

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      relative-build-root: bazel-bin/build
      label: normal
      build-name: ${{ env.BUILD_NAME }}
      aarch64: false

  autodoc:
    runs-on: ubuntu-latest-kong
    needs: build
    steps:
      - name: Install packages
        run: sudo apt update && sudo apt install -y libyaml-dev valgrind libprotobuf-dev libpam-dev jq httpie

      - name: Checkout Kong source code
        uses: actions/checkout@v3
        with:
          path: kong
          ref: ${{ github.event.inputs.source_branch }}

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-normal
          path: .

      - name: Extract the artifact contents
        run: |
          sudo tar -C /usr/local/ -xzvf artifacts/build-${{ env.BUILD_NAME_NORMAL }}.tar.gz
          sudo mkdir -p ${{ env.BUILD_ROOT }}/${{ env.BUILD_NAME_NORMAL }}
          sudo tar -C ${{ env.BUILD_ROOT }}/${{ env.BUILD_NAME_NORMAL }} -xzvf artifacts/build-${{ env.BUILD_NAME_NORMAL }}.tar.gz

      - name: Install Kong dev
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_KONG_BOT_READ_TOKEN }}
        run: make dev LIBRARY_PREFIX=/usr/local/kong

      - name: Checkout Kong Docs
        uses: actions/checkout@v3
        with:
          repository: kong/docs.konghq.com
          path: docs.konghq.com
          token: ${{ secrets.GHA_KONG_BOT_READ_TOKEN }}
          ref: ${{ github.event.inputs.target_branch }}

      - name: Run Autodocs
        run: |
          cd kong
          source ${{ env.BUILD_ROOT }}/${{ env.BUILD_NAME_NORMAL }}-venv.sh
          scripts/autodoc ../docs.konghq.com ${{ github.event.inputs.version }}

      - name: Generate branch name
        id: kong-branch
        run: |
          cd kong
          output="$(git branch --show-current)"
          echo "name=$output" >> $GITHUB_OUTPUT

      - name: Show Docs status
        run: |
          cd docs.konghq.com
          git status
          git checkout -b "autodocs-${{ steps.kong-branch.outputs.name }}"

      - name: Commit autodoc changes
        uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5.0.1
        with:
          repository: "./docs.konghq.com"
          commit_message: "Autodocs update"
          branch: "autodocs-${{ steps.kong-branch.outputs.name }}"
          skip_fetch: true
          push_options: "--force"

      - name: Raise PR
        run: |
          cd docs.konghq.com
          echo "${{ secrets.GHA_KONG_BOT_READ_TOKEN }}" | gh auth login --with-token
          gh pr create --base "${{ github.event.inputs.target_branch }}" --fill --label "review:autodoc"
