name: Build & Test
on: [push]

jobs:
  build:
    name: Build dependencies
    runs-on: ubuntu-20.04

    steps:
    - name: Set environment variables
      run: |
          echo "INSTALL_ROOT=$HOME/install-root" >> $GITHUB_ENV
          echo "DOWNLOAD_ROOT=$HOME/download-root" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$INSTALL_ROOT/openssl/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

    - name: Checkout Kong source code
      uses: actions/checkout@v2

    - name: Lookup build cache
      uses: actions/cache@v2
      id: cache-deps
      with:
        path: ${{ env.INSTALL_ROOT }}
        key: ${{ hashFiles('.ci/setup_env_github.sh') }}-${{ hashFiles('.github/workflows/build_and_test.yml') }}-${{ hashFiles('.requirements') }}-${{ hashFiles('kong-*.rockspec') }}-${{ hashFiles('Makefile') }}

    - name: Checkout kong-build-tools
      if: steps.cache-deps.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: Kong/kong-build-tools
        path: kong-build-tools
        ref: 4.25.3

    - name: Checkout go-pluginserver
      if: steps.cache-deps.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: Kong/go-pluginserver
        path: go-pluginserver

    - name: Add to Path
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
          echo "$INSTALL_ROOT/openssl/bin" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/openresty/nginx/sbin" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/openresty/bin" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/luarocks/bin" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/kong-build-tools/openresty-build-tools" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/bin" >> $GITHUB_PATH

    - name: Install packages
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: sudo apt update && sudo apt install libyaml-dev valgrind libprotobuf-dev libpam-dev

    - name: Build Kong dependencies
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
          export CACHE_DIR=$INSTALL_ROOT/distributions-cache
          source .ci/setup_env_github.sh
          make dev 
          make try-install-plugins-ee


  lint-doc-and-unit-tests:
    name: Lint, Doc and Unit tests
    runs-on: ubuntu-20.04
    needs: build

    env:
      KONG_TEST_PG_DATABASE: kong
      KONG_TEST_PG_USER: kong

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: kong
          POSTGRES_DB: kong
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 5s --health-timeout 5s --health-retries 8

    steps:
    - name: Set environment variables
      run: |
          echo "INSTALL_ROOT=$HOME/install-root" >> $GITHUB_ENV
          echo "DOWNLOAD_ROOT=$HOME/download-root" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$INSTALL_ROOT/openssl/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

    - name: Checkout Kong source code
      uses: actions/checkout@v2

    - name: Lookup build cache
      uses: actions/cache@v2
      id: cache-deps
      with:
        path: ${{ env.INSTALL_ROOT }}
        key: ${{ hashFiles('.ci/setup_env_github.sh') }}-${{ hashFiles('.github/workflows/build_and_test.yml') }}-${{ hashFiles('.requirements') }}-${{ hashFiles('kong-*.rockspec') }}-${{ hashFiles('Makefile') }}

    - name: Add to Path
      run: |
          echo "$INSTALL_ROOT/openssl/bin" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/openresty/nginx/sbin" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/openresty/bin" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/luarocks/bin" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/kong-build-tools/openresty-build-tools" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/bin" >> $GITHUB_PATH
    
    - name: Create symbolic links
      run: |
          sudo ln -s $(realpath ${INSTALL_ROOT}/libpasswdqc/lib/libpasswdqc.so) /lib/libpasswdqc.so

    - name: Check autodoc generation
      run: |
          eval `luarocks path`
          scripts/autodoc

    - name: Check Admin API definition generation
      run: |
          eval `luarocks path`
          scripts/gen-admin-api-def.sh

    - name: Lint Lua code
      run: |
          eval `luarocks path`
          make lint

    - name: Unit tests
      run: |
          eval `luarocks path`
          make dev 
          make try-install-plugins-ee
          bin/busted -v -o htest spec/01-unit spec-ee/01-unit

  integration-tests-postgres:
    name: Postgres ${{ matrix.suite }} - ${{ matrix.split }} tests
    runs-on: ubuntu-20.04
    needs: build

    strategy:
      matrix:
        suite: [integration, plugins]
        split: [first-CE, second-CE, first-EE, second-EE, third-EE]
        exclude:
          - suite: plugins
            split: second-EE
          - suite: plugins
            split: third-EE

    env:
      KONG_VERSION: nightly-ee
      DOCKER_IMAGE_NAME: kong-ee-test
      KONG_TEST_PG_DATABASE: kong
      KONG_TEST_PG_USER: kong
      KONG_TEST_DATABASE: postgres
      TEST_SUITE: ${{ matrix.suite }}
      TEST_SPLIT: ${{ matrix.split }}

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: kong
          POSTGRES_DB: kong
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 5s --health-timeout 5s --health-retries 8

      grpcbin:
        image: moul/grpcbin
        ports:
          - 15002:9000
          - 15003:9001

      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

      zipkin:
        image: openzipkin/zipkin:2.19
        ports:
          - 9411:9411

    steps:
    - name: Set environment variables
      run: |
          echo "INSTALL_ROOT=$HOME/install-root" >> $GITHUB_ENV
          echo "DOWNLOAD_ROOT=$HOME/download-root" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$INSTALL_ROOT/openssl/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

    - name: Checkout Kong source code
      uses: actions/checkout@v2

    - name: Lookup build cache
      uses: actions/cache@v2
      id: cache-deps
      with:
        path: ${{ env.INSTALL_ROOT }}
        key: ${{ hashFiles('.ci/setup_env_github.sh') }}-${{ hashFiles('.github/workflows/build_and_test.yml') }}-${{ hashFiles('.requirements') }}-${{ hashFiles('kong-*.rockspec') }}-${{ hashFiles('Makefile') }}

    - name: Add to Path
      run: |
          echo "$INSTALL_ROOT/openssl/bin" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/openresty/nginx/sbin" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/openresty/bin" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/luarocks/bin" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/kong-build-tools/openresty-build-tools" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/bin" >> $GITHUB_PATH

    - name: Create symbolic links
      run: |
          sudo ln -s $(realpath ${INSTALL_ROOT}/libpasswdqc/lib/libpasswdqc.so) /lib/libpasswdqc.so

    - name: Add gRPC test host names
      run: |
          echo "127.0.0.1 grpcs_1.test" | sudo tee -a /etc/hosts
          echo "127.0.0.1 grpcs_2.test" | sudo tee -a /etc/hosts

    - name: Tests
      env:
        PULP_USERNAME: ${{ secrets.PULP_USERNAME }}
        PULP_PASSWORD: ${{ secrets.PULP_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.GHA_DOCKERHUB_PULL_USER }}
        DOCKER_PASSWORD: ${{ secrets.GHA_KONG_ORG_DOCKERHUB_PULL_TOKEN }}
      run: |
          eval `luarocks path`
          make dev 
          make try-install-plugins-ee
          .ci/run_tests_github.sh

  integration-tests-dbless:
    name: DB-less integration tests
    runs-on: ubuntu-20.04
    needs: build

    env:
      KONG_TEST_PG_DATABASE: kong
      KONG_TEST_PG_USER: kong
      KONG_TEST_DATABASE: 'off'
      TEST_SUITE: dbless

    services:
      grpcbin:
        image: moul/grpcbin
        ports:
          - 15002:9000
          - 15003:9001

    steps:
    - name: Set environment variables
      run: |
          echo "INSTALL_ROOT=$HOME/install-root" >> $GITHUB_ENV
          echo "DOWNLOAD_ROOT=$HOME/download-root" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$INSTALL_ROOT/openssl/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "CACHE_DIR=$INSTALL_ROOT/distributions-cache" >> $GITHUB_ENV

    - name: Checkout Kong source code
      uses: actions/checkout@v2

    - name: Lookup build cache
      uses: actions/cache@v2
      id: cache-deps
      with:
        path: ${{ env.INSTALL_ROOT }}
        key: ${{ hashFiles('.ci/setup_env_github.sh') }}-${{ hashFiles('.github/workflows/build_and_test.yml') }}-${{ hashFiles('.requirements') }}-${{ hashFiles('kong-*.rockspec') }}-${{ hashFiles('Makefile') }}

    - name: Add to Path
      run: |
          echo "$INSTALL_ROOT/openssl/bin" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/openresty/nginx/sbin" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/openresty/bin" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/luarocks/bin" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/kong-build-tools/openresty-build-tools" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/bin" >> $GITHUB_PATH

    - name: Create symbolic links
      run: |
          sudo ln -s $(realpath ${INSTALL_ROOT}/libpasswdqc/lib/libpasswdqc.so) /lib/libpasswdqc.so

    - name: Add gRPC test host names
      run: |
          echo "127.0.0.1 grpcs_1.test" | sudo tee -a /etc/hosts
          echo "127.0.0.1 grpcs_2.test" | sudo tee -a /etc/hosts

    - name: Tests
      env:
        PULP_USERNAME: ${{ secrets.PULP_USERNAME }}
        PULP_PASSWORD: ${{ secrets.PULP_PASSWORD }}
      run: |
          eval `luarocks path`
          make dev 
          make try-install-plugins-ee
          .ci/run_tests_github.sh

  integration-tests-cassandra:
    name: C* 3 ${{ matrix.suite }} - ${{ matrix.split }} tests
    runs-on: ubuntu-20.04
    needs: build

    strategy:
      matrix:
        suite: [integration, plugins]
        split: [first-CE, second-CE, first-EE, second-EE, third-EE]
        exclude:
          - suite: plugins
            split: second-EE
          - suite: plugins
            split: third-EE

    env:
      DOCKER_IMAGE_NAME: kong-ee-test
      KONG_TEST_DATABASE: cassandra
      TEST_SUITE: ${{ matrix.suite }}
      TEST_SPLIT: ${{ matrix.split }}

    services:
      cassandra:
        image: cassandra:3
        ports:
          - 7199:7199
          - 7000:7000
          - 9160:9160
          - 9042:9042
        options: --health-cmd "cqlsh -e 'describe cluster'" --health-interval 5s --health-timeout 5s --health-retries 8

      grpcbin:
        image: moul/grpcbin
        ports:
          - 15002:9000
          - 15003:9001

      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

      zipkin:
        image: openzipkin/zipkin:2.19
        ports:
          - 9411:9411

    steps:
    - name: Set environment variables
      run: |
          echo "INSTALL_ROOT=$HOME/install-root" >> $GITHUB_ENV
          echo "DOWNLOAD_ROOT=$HOME/download-root" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$INSTALL_ROOT/openssl/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "DOCKER_CACHE=$HOME/docker-cache" >> $GITHUB_ENV

    - name: Checkout Kong source code
      uses: actions/checkout@v2

    - name: Lookup build cache
      uses: actions/cache@v2
      id: cache-deps
      with:
        path: ${{ env.INSTALL_ROOT }}
        key: ${{ hashFiles('.ci/setup_env_github.sh') }}-${{ hashFiles('.github/workflows/build_and_test.yml') }}-${{ hashFiles('.requirements') }}-${{ hashFiles('kong-*.rockspec') }}-${{ hashFiles('Makefile') }}

    - name: Add to Path
      run: |
          echo "$INSTALL_ROOT/openssl/bin" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/openresty/nginx/sbin" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/openresty/bin" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/luarocks/bin" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/kong-build-tools/openresty-build-tools" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/bin" >> $GITHUB_PATH
    
    - name: Create symbolic links
      run: |
          sudo ln -s $(realpath ${INSTALL_ROOT}/libpasswdqc/lib/libpasswdqc.so) /lib/libpasswdqc.so

    - name: Add gRPC test host names
      run: |
          echo "127.0.0.1 grpcs_1.test" | sudo tee -a /etc/hosts
          echo "127.0.0.1 grpcs_2.test" | sudo tee -a /etc/hosts

    - name: Tests
      env:
        PULP_USERNAME: ${{ secrets.PULP_USERNAME }}
        PULP_PASSWORD: ${{ secrets.PULP_PASSWORD }}
      run: |
          eval `luarocks path`
          make dev 
          make try-install-plugins-ee
          .ci/run_tests_github.sh

  pdk-tests:
    name: PDK tests
    runs-on: ubuntu-20.04
    needs: build

    env:
      TEST_SUITE: pdk

    steps:
    - name: Set environment variables
      run: |
          echo "INSTALL_ROOT=$HOME/install-root" >> $GITHUB_ENV
          echo "DOWNLOAD_ROOT=$HOME/download-root" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$INSTALL_ROOT/openssl/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "CACHE_DIR=$INSTALL_ROOT/distributions-cache" >> $GITHUB_ENV

    - name: Checkout Kong source code
      uses: actions/checkout@v2

    - name: Lookup build cache
      uses: actions/cache@v2
      id: cache-deps
      with:
        path: ${{ env.INSTALL_ROOT }}
        key: ${{ hashFiles('.ci/setup_env_github.sh') }}-${{ hashFiles('.github/workflows/build_and_test.yml') }}-${{ hashFiles('.requirements') }}-${{ hashFiles('kong-*.rockspec') }}-${{ hashFiles('Makefile') }}

    - name: Add to Path
      run: |
          echo "$INSTALL_ROOT/openssl/bin" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/openresty/nginx/sbin" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/openresty/bin" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/luarocks/bin" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/kong-build-tools/openresty-build-tools" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/bin" >> $GITHUB_PATH

    - name: Create symbolic links
      run: |
          sudo ln -s $(realpath ${INSTALL_ROOT}/libpasswdqc/lib/libpasswdqc.so) /lib/libpasswdqc.so

    - name: Install Test::Nginx
      run: |
          CPAN_INSTALL=$INSTALL_ROOT/bin
          mkdir -p $CPAN_INSTALL
          curl -o $CPAN_INSTALL/cpanm https://cpanmin.us
          chmod +x $CPAN_INSTALL/cpanm

          echo "Installing CPAN dependencies..."
          cpanm --notest --local-lib=$HOME/perl5 local::lib && eval $(perl -I $HOME/perl5/lib/perl5/ -Mlocal::lib)
          cpanm --notest Test::Nginx

    - name: Tests
      env:
        PULP_USERNAME: ${{ secrets.PULP_USERNAME }}
        PULP_PASSWORD: ${{ secrets.PULP_PASSWORD }}
      run: |
          eval `luarocks path`
          make dev 
          make try-install-plugins-ee

          eval $(perl -I $HOME/perl5/lib/perl5/ -Mlocal::lib)
          .ci/run_tests_github.sh

  plugins-ee-tests:
    name: plugins EE - ${{ matrix.split }} tests
    runs-on: ubuntu-20.04
    needs: build

    strategy:
      matrix:
        split: 
        - first
        - second
        - third
        - fourth

    env:
      KONG_VERSION: '2.8.0.0'
      TEST_SUITE: plugins-ee
      TEST_SPLIT: ${{ matrix.split }}

    steps:
    - name: Set environment variables
      run: |
          echo "INSTALL_ROOT=$HOME/install-root" >> $GITHUB_ENV
          echo "DOWNLOAD_ROOT=$HOME/download-root" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$INSTALL_ROOT/openssl/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "DOCKER_CACHE=$HOME/docker-cache" >> $GITHUB_ENV

    - name: Checkout Kong source code
      uses: actions/checkout@v3

    - name: Lookup build cache
      uses: actions/cache@v3
      id: cache-deps
      with:
        path: ${{ env.INSTALL_ROOT }}
        key: ${{ hashFiles('.ci/setup_env_github.sh') }}-${{ hashFiles('.github/workflows/build_and_test.yml') }}-${{ hashFiles('.requirements') }}-${{ hashFiles('kong-*.rockspec') }}-${{ hashFiles('Makefile') }}

    - name: Install packages
      run: sudo apt update && sudo apt install libyaml-dev valgrind libprotobuf-dev libpam-dev

    - name: Add to Path
      run: |
          echo "$INSTALL_ROOT/openssl/bin" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/openresty/nginx/sbin" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/openresty/bin" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/luarocks/bin" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/kong-build-tools/openresty-build-tools" >> $GITHUB_PATH
          echo "$INSTALL_ROOT/bin" >> $GITHUB_PATH

    - name: Tests
      env:
        PULP_USERNAME: ${{ secrets.PULP_USERNAME }}
        PULP_PASSWORD: ${{ secrets.PULP_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.GHA_DOCKERHUB_PULL_USER }}
        DOCKER_PASSWORD: ${{ secrets.GHA_KONG_ORG_DOCKERHUB_PULL_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
          .ci/run_tests_github.sh