name: Changelog Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]
    # only run when these files have changed
    paths:
      - 'changelog/**/**.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{github.event.pull_request.head.repo.full_name}}
          ref: ${{github.event.pull_request.head.ref}}
          submodules: false
      - uses: jschmid1/chatgpt-action@7255d6fc6efcd1e7996e402463cb86a14ee97463
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false
          action: review
          path_filters: "changelog/**/**.yml"
          review_comment_lgtm: false
          custom_prompt_path: ".github/workflows/styleguide/changelog-prompt.txt"
