name: Lint

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master
      - next/*
      - release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lua-check:
    name: Lua Check
    runs-on: ubuntu-latest-kong
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    if: (github.actor != 'dependabot[bot]')

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    # Optional step to run on only changed files
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@0874344d6ebbaa00a27da73276ae7162fadcaf69 # v37
      with:
        files: |
          **.lua

    - name: Get changed spec files
      id: changed-spec-files
      uses: tj-actions/changed-files@0874344d6ebbaa00a27da73276ae7162fadcaf69 # v37
      with:
        files: |
          spec/**
          spec-ee/**

    - name: Lua Check
      uses: Kong/public-shared-actions/code-check-actions/lua-lint@a98be0184f832cb24a9dd233f99074e8ba17b488 # v2.3.3
      with:
        additional_args: '--no-default-config --config .luacheckrc --exclude-files ./distribution/'
        # Point to the /dev/null file if no files are changed.
        # This action commented out the linting errors in PR,
        # and the author might have already fixed that but no Lua files are changed
        # (e.g. reset branch to target branch, and changed some CI files only),
        # the outdated comments should be updated in this case.
        # Pointing to /dev/null make the action to lint a empty file,
        # empty file will not have any linting errors,
        # so the action will update the outdated comments in PR.
        files: ${{ steps.changed-files.outputs.any_changed == 'true' && steps.changed-files.outputs.all_changed_files || '/dev/null' }}
        action_fail: true # Fail the action if the linting fails

    - name: Check spec and copyright-header
      if: steps.changed-spec-files.outputs.any_changed == 'true'
      run: |
        make sca

    - name: Validate rockspec file
      run: |
        sudo apt-get update && sudo apt-get install -y luarocks
        sudo luarocks install luacheck
        scripts/validate-rockspec
