name: Package & Release Scheduler

on:  # yamllint disable-line rule:truthy
  schedule:
  - cron:  '0 0 * * *'
  workflow_dispatch:

permissions:
  actions: write # required for dispatch API

jobs:
 dispatch:
    strategy:
      matrix:
        include:
          # non "active" branch are build every 3 days to reduce workload
          # on github actions runners
          - branch: master
            version: "nightly"
            active_branch: "yes"
          - branch: next/3.4.x.x
            version: "3.4.x.x"
            active_branch: "yes"
          - branch: next/3.3.x.x
            version: "3.3.x.x"
          - branch: next/3.2.x.x
            version: "3.2.x.x"
          - branch: next/3.1.x.x
            version: "3.1.x.x"
          - branch: next/2.8.x.x
            version: "2.8.x.x"
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - name: Find date
        id: date
        run: |
            d=$(date "+%-d") # strip leading zero
            dmod=$(($d % 3))
            echo "dmod=$dmod" >> $GITHUB_OUTPUT

      # we want to be pushing the same tag and gh release for nightlies
      - name: Upsert Nightly Tag
        if: matrix.branch == 'master'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        uses: richardsimko/update-tag@v1
        with:
          tag_name: nightly

      - name: Daily build Dispatch
        uses: benc-uk/workflow-dispatch@798e70c97009500150087d30d9f11c5444830385 # v1
        if: matrix.active_branch == 'yes' || steps.date.outputs.dmod == '1'
        with:
          workflow: release.yml
          ref: ${{ matrix.branch }}
          inputs: '{"official":"false", "version":"${{ matrix.version }}"}'

