name: Package & Release Scheduler

on:  # yamllint disable-line rule:truthy
  schedule:
  - cron:  '0 0 * * *'

permissions:
  actions: write # required for dispatch API

jobs:
 dispatch:
    strategy:
      matrix:
        include:
          - branch: master
            version: "nightly"
          - branch: next/3.1.x.x
            version: "3.1.x.x"
          - branch: next/2.8.x.x
            version: "2.8.x.x"
    runs-on: ubuntu-latest
    steps:
      - name: Daily build Dispatch
        uses: benc-uk/workflow-dispatch@798e70c97009500150087d30d9f11c5444830385 # v1
        with:
          workflow: release.yml
          ref: ${{ matrix.branch }}
          inputs: '{"official":"false", "version":"${{ matrix.version }}"}'
 