name: Package & Release Scheduler

on:  # yamllint disable-line rule:truthy
  schedule:
  - cron:  '0 0 * * *'
  workflow_dispatch:

permissions:
  actions: write # required for dispatch API

jobs:
 dispatch:
    strategy:
      matrix:
        include:
          # non "active" branch are build every 3 days to reduce workload
          # on github actions runners
          - branch: master
            version: "nightly"
            active_branch: "yes"
          - branch: next/3.9.x.x
            version: "3.9.x.x"
            active_branch: "yes"
          - branch: next/3.8.x.x
            version: "3.8.x.x"
          - branch: next/3.7.x.x
            version: "3.7.x.x"
          - branch: next/3.6.x.x
            version: "3.6.x.x"
          - branch: next/3.4.x.x
            version: "3.4.x.x"
          - branch: next/2.8.x.x
            version: "2.8.x.x"
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - name: Find date
        id: date
        run: |
            d=$(date "+%-d") # strip leading zero
            dmod=$(($d % 3))
            echo "dmod=$dmod" >> $GITHUB_OUTPUT

      # we want to be pushing the same tag and gh release for nightlies
      - name: Upsert Nightly Tag
        if: matrix.branch == 'master'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        uses: richardsimko/update-tag@v1
        with:
          tag_name: nightly

      - name: Random delay up to 5 minutes
        run: |
          MINWAIT=0
          MAXWAIT=300
          delay=$((MINWAIT+RANDOM % (MAXWAIT-MINWAIT)))
          echo "Delay for $delay seconds..."
          sleep $delay

      - name: Daily build Dispatch
        uses: benc-uk/workflow-dispatch@e2e5e9a103e331dad343f381a29e654aea3cf8fc # v1
        if: matrix.active_branch == 'yes' || steps.date.outputs.dmod == '1'
        with:
          workflow: release.yml
          ref: ${{ matrix.branch }}
          inputs: '{"official":"false", "version":"${{ matrix.version }}"}'

