name: OpenSSF scorecards
on:
  branch_protection_rule:
    types: [created, edited, deleted]
  pull_request:
    paths-ignore:
    # ignore top-level markdown files (CHANGELOG.md, README.md, etc.)
    - '*.md'
  push: 
    branches:
      - master
    paths-ignore:
      # ignore top-level markdown files (CHANGELOG.md, README.md, etc.)
      - '*.md'
      # ignore PRs for the generated COPYRIGHT file
      - 'COPYRIGHT'

permissions: read-all

jobs:
  analysis:
    name: Scorecards analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
      - name: "Checkout code"
        continue-on-error: true
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          persist-credentials: false

      - name: "Run analysis"
        continue-on-error: true
        uses: ossf/scorecard-action@99c53751e09b9529366343771cc321ec74e9bd3d # v2.0.6
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.SECURITY_BOT_TOKEN }}
      - name: "Show scores from JSON"
        continue-on-error: true
        run: cat results.sarif | jq .runs[].results

