name: Upgrade Tests

on:
  pull_request:
    paths:
    - 'scripts/upgrade-tests/**'
    - 'kong/db/migrations/**'
    - 'spec/05-migration/**'
    - 'kong/enterprise_edition/db/migrations/**'
    - '.github/workflows/upgrade-tests.yml'
    - 'kong/plugins/*/migrations/**'
    - 'plugins-ee/**/migrations/**'
  push:
    paths-ignore:
    # ignore markdown files (CHANGELOG.md, README.md, etc.)
    - '**/*.md'
    branches:
    - master
    - release/*
    - test-please/*
# cancel previous runs if new commits are pushed to the PR, but run for each commit on master
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  upgrade-test:
    name: Run migration tests
    runs-on: ${{ vars.RUNS_ON }}

    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get -y install jq

      - name: Clone Kong source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run upgrade tests
        run: |
          bash -x ./scripts/upgrade-tests/test-upgrade-path.sh
